import Head from 'next/head';
import Footer from './Footer';
import NavigationBar from './NavBar';

export default function Layout({ children }) {
  return (
    <>
        <Head>
            <title>Service Learning</title>
            <meta name="description" content="Generated by create next app" /> {/** TODO ADD DESCRIPTION */}
            <meta name="keywords" content="environment, carbon footprint, save the planet" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* <NavigationBar /> */}
        <main>{children}</main>
        <Footer/>
    </>
  )
}