import Head from 'next/head';
import NavigationBar from '../components/NavBar';
import styles from '../styles/Minigame.module.css';

export default function Minigame() {
    return (
        <div>
            <Head>
                <title>Service Learning</title>
                <meta name="description" content="Generated by create next app" /> {/** TODO ADD DESCRIPTION */}
                <meta name="keywords" content="environment, carbon footprint, save the planet, clicker" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div className={styles.main_game}>

                </div>
            </main>
        </div>
    );
}